#!/bin/bash

CC_MAIN_SCRIPT_PARTIAL="cherry-soda/cli/main.js"
DIRNAME=$(dirname "$0")

if [[ $DIRNAME == *node_modules/.bin ]]; then
  CC_MAIN_SCRIPT="${DIRNAME//.bin/$CC_MAIN_SCRIPT_PARTIAL}"
else
  CC_MAIN_SCRIPT="${DIRNAME}/main.js"
fi

/usr/bin/env bun --hot "$CC_MAIN_SCRIPT" -- "$@"

#if [[ "$*" == *"--node"* ]]; then
#  /usr/bin/env node "$CC_MAIN_SCRIPT" -- "$@"
#elif command /usr/bin/env bun &>/dev/null; then
#  /usr/bin/env bun "$CC_MAIN_SCRIPT" -- "$@"
#elif command /usr/bin/env node &>/dev/null; then
#  /usr/bin/env node "$CC_MAIN_SCRIPT" -- "$@"
#fi
