#!/usr/bin/env bun

import path from 'path'

const mainScriptPartial = 'cherry-soda/cli/main.js'
const dirname = path.dirname((new URL(import.meta.url ?? 'file://' + __filename)).pathname)

const mainScriptPath = dirname.endsWith('node_modules/.bin')
    ? dirname.replace('.bin', mainScriptPartial)
    : `${dirname}/main.js`

await import(mainScriptPath)
