#!/usr/bin/env/ node

import path from 'path'

const mainScriptName = 'main.js'
const mainScriptPartial = path.join('cherry-soda', 'cli', mainScriptName)
const dirname = (new URL(import.meta.url)).pathname
let mainScriptPath

if (dirname.includes('node_modules/.bin'))
  mainScriptPath = dirname.replace('.bin', mainScriptPartial)
else
  mainScriptPath = path.join(dirname, mainScriptName)

import(mainScriptPath)
